### ISSUE TITLE
有内存泄漏的问题

### ISSUE THREAD

**Issue by TheMandalorianHub** [soulqw/Curtain#10]
传递actiivty进去，一些界面来回跳转后用AS去监测有内存泄漏的问题

**Comment by soulqw** [comment]
@Youdau  我这边正常使用没有发现内存泄露，你这边可以贴出泄漏堆栈一起看看

**Comment by TheMandalorianHub** [comment]
<img width="1596" alt="截屏2021-01-19 下午5 55 02" src="https://user-images.githubusercontent.com/22392640/105018039-78dc9300-5a7f-11eb-8092-18928d312955.png">
泄漏指向的地方是高亮的view，我给加了弱引用修复掉了。。。

**Comment by TheMandalorianHub** [comment]
另外高亮的view在一些刘海屏手机上镂空的位置有偏离不准确，是因为在那些手机上计算的屏幕高度不一致的问题导致的

**Comment by soulqw** [comment]
@Youdau 感谢提供issue，库可以提供自动指定偏移量，那个偏离不准你这边可以帮我改点适配代码验证一下么？
