### ISSUE TITLE
不支持高亮区域的点击诶。我高亮一个按钮，直接点击这个按钮 也是很合情合理的吧。

### ISSUE THREAD

**Issue by wojiaoliushe** [soulqw/Curtain#11]
不知大佬可否补充一下，不胜感激

**Comment by soulqw** [comment]
@wojiaoliushe 这个后续可以支持，目前情况可以给个思路参考：
https://github.com/soulqw/Curtain/issues/9

**Comment by soulqw** [comment]
@wojiaoliushe 0.2.0已经支持，参考最新ReadMe 更多使用姿势
