### ISSUE TITLE
高亮的View无法响应点击事件

### ISSUE THREAD

**Issue by mudelong** [soulqw/Curtain#16]
您好，在开发中我发现curtain.with(原界面中高亮的按钮)，此时按钮原有的点击事件不响应了。请问如何能让高亮的view响应他原来的点击？

**Comment by mudelong** [comment]
补充一下，我是在Fragment里用的

**Comment by soulqw** [comment]
@mudelong 0.2.0已经支持，参考最新ReadMe 更多使用姿势
