### ISSUE TITLE
在华为Mate40Pro手机上，高亮区域会向右侧偏移

### ISSUE THREAD

**Issue by LiuXingzhou** [soulqw/Curtain#19]
如图所示
![QtScrcpy_20220107_091430_740](https://user-images.githubusercontent.com/24751840/148475261-bc6eeff8-f7f2-4775-a051-ec5b851f4b54.png)

**Comment by LiuXingzhou** [comment]
华为Mate40Pro上使用：
int[] viewWLocation = new int[2];
info.targetView.getLocationInWindow(viewWLocation);
获取目标View的坐标点有问题。

**Comment by soulqw** [comment]
@LiuXingzhou 华为系统有其他方法获取？

**Comment by soulqw** [comment]
@LiuXingzhou 按需用offset方法吧：
Curtain.withOffset
