### ISSUE TITLE
应该是存在bug的，控件的定位

### ISSUE THREAD

**Issue by HysonHou** [soulqw/Curtain#20]
![image](https://user-images.githubusercontent.com/13035957/149144749-9ed20f58-1981-477f-82df-e41d86910c72.png)

**Comment by soulqw** [comment]
@Hynsn 什么机型？ demo上正常么？

**Comment by HysonHou** [comment]
> @Hynsn 什么机型？ demo上正常么？

ViewPager中嵌套Fragment
