### ISSUE TITLE
请问你为什么这样获取屏幕宽高并且这样设置

### ISSUE THREAD

**Issue by daxuNo** [soulqw/Curtain#23]
这样获取的屏幕宽高并不正确特别是全面屏和异形屏
![q](https://user-images.githubusercontent.com/37949811/177687128-51117805-21d8-4105-beff-3660eadde213.png)
![fang](https://user-images.githubusercontent.com/37949811/177687122-93f8e463-fa3b-4ae5-bf1c-1b7989e029e0.png)

**Comment by soulqw** [comment]
@daxuNo 你这边有什么方法推荐么？
