### ISSUE TITLE
能提供回调操作知道 view 吗

### ISSUE THREAD

**Issue by GoblinV** [soulqw/Curtain#26]

**Comment by soulqw** [comment]
`setCallBack(new Curtain.CallBack() {
                    @Override
                    public void onShow(IGuide curtain) {
                        //get top view when curtain showed
                        Log.d(TAG, "on guide show: " + curtain.getCurrentTopView()
                                + "\n and size is" + curtain.getCurrentTopView().getWidth() + " " + curtain.getCurrentTopView().getHeight());
                    }

                    @Override
                    public void onDismiss(IGuide iGuide) {

                    }
                })`
