### ISSUE TITLE
上下左右，位置不能设置吗

### ISSUE THREAD

**Issue by clj12081103** [soulqw/Curtain#3]

**Comment by soulqw** [comment]
高亮部分以View作为基本单位和卯点，可横向或纵向偏移，如果有不理解的地方，可细致描述一下

**Comment by woaimi520** [comment]
请问这里移动是调用哪个函数 找到一个位移 是移动整个蒙层的会把高亮部分也位移了

**Comment by soulqw** [comment]
@woaimi520 Curtain.withOffset
