### ISSUE TITLE
ImageView设置src图片，如果有透明部分，不支持吗？

### ISSUE THREAD

**Issue by ZhuSky** [soulqw/Curtain#4]
![image](https://user-images.githubusercontent.com/18596232/81645108-8d31b000-945b-11ea-941b-7ffbd8d66e10.png)

**Comment by soulqw** [comment]
@ZhuSky  这种情况下，你可以使用withShape 的方式去高亮，使用默认提供的CircleShape ，后面如果你有其它需求，也可以自定义Shape，自己绘制这个区域

**Comment by ZhuSky** [comment]
withShape 可以解决此问题，多谢🙏
