### ISSUE TITLE
空白区域点击事件传递

### ISSUE THREAD

**Issue by 13120241790** [soulqw/Curtain#5]
您好，咱们库支持高亮区域点击事件传递下去吗，比如我高亮区域是个按钮。点击空白区域的按钮 
1 蒙层关闭 2 随后触发按钮后续的业务点击事件。我现在在 demo 里面修改空白区域的点击事件代码如下:
RecyclerViewActivity.java 
  @Override
        public void onBindViewHolder(@NonNull RecyclerView.ViewHolder holder, int position) {
            ((TextView) (holder.itemView.findViewById(R.id.tv_text))).setText(data[position]);
            holder.itemView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    Toast.makeText(RecyclerViewActivity.this, "toast", Toast.LENGTH_SHORT).show();
                }
            });
        }

目前是不支持。能否提供这种支持，或者指点一下应该怎么弄我自己来尝试修改然后 pull request 增加这种支持。

**Comment by soulqw** [comment]
@13120241790  非常感谢提供意见，你可以描述下你的想法然后代码提到Dev 分支，后面我抽时间看看

**Comment by soulqw** [comment]
@13120241790 0.2.0已经支持，参考最新ReadMe 更多使用姿势
