### ISSUE TITLE
点击事件

### ISSUE THREAD

**Issue by kdwu** [soulqw/Curtain#9]
设置成高亮的View就不能设置点击事件了吗？

**Comment by soulqw** [comment]
@kdwu 
蒙层是一个Dialog，默认是截获所有点击事件的。
给一个思路： setTopView的时候，在高亮的区域制定一个看不见的View，对这个View设置点击事件，然后将弹框Dismiss，同时将被高亮对View perfermOnClick 即可

**Comment by soulqw** [comment]
@kdwu 0.2.0已经支持，参考最新ReadMe 更多使用姿势
